### ISSUE TITLE
Update higher levels of the path above zone

### ISSUE THREAD

**Issue by rggibb** [opengeospatial/ogcapi-discrete-global-grid-systems#24]
This work item should be based on slides 5 & 6 as follows in the Developer Track presentation:

![image](https://user-images.githubusercontent.com/7731644/122189088-bb968000-cee4-11eb-833d-c9725a9117e8.png)

![image](https://user-images.githubusercontent.com/7731644/122189173-cea95000-cee4-11eb-99da-2ff3fedfb2fc.png)

This information ma ynot be sufficiently complete, in which case discussion with @geofizzydrink will be needed.

**Comment by jerstlouis** [comment]
Closing this issue as it is mostly obsoleted by events:

- The ability to retrieve zones as features is supported by the Zone Query conformance class as `.../dggs/{dggrsId}/zones`, with the ability to negotiate a GeoJSON or FG-JSON representation of the zones (whether as centroid points or zone polygons/polyhedrons/prims). This can be all zones of a particular refinement level of a DGGH, all zones where there is data for a particular collection, or all zones matching a particular query
- The topological relationship can be described in the Zone Information resource (`.../dggs/{dggrsId}/zones/{zoneId}`) as using the link relation types `[ogc-rel:dggs-zone-parent]`, `[ogc-rel:dggs-zone-child]` and `[ogc-rel:dggs-zone-neighbor]`, but this is only a recommendation for purposes of demonstration / education / debugging. Clients should not rely on Web APIs to determine zone relationships, since that is very inefficient. Instead they should have their own local software library with a built-in understanding of the DGGRS they wish to use.
