### ISSUE TITLE
Questions re. DGGS Set and Query functions

### ISSUE THREAD

**Issue by recalcitrantsupplant** [opengeospatial/ogcapi-discrete-global-grid-systems#35]
A short set of questions, happy to split these out as necessary depending on the answers:

DGGS Set Functions:
1. Sibling - Is this the same as neighbours? I.e. the ZonalIDs immediately arround a given ZonalID, or is it children of the ZonalID’s parent? As a follow on, if they're different, would it be worth having both?
2. Parent - parent returns all parents currently, would it be useful to have a split between the immediate parent and others, e.g. parent vs. ancestors (all parents)

DGGS Query Functions:
3. Is ‘overlaps’ valid for two ZonaIDs? (I was initially thinking for rHEALPix, I realise now it is probably valid for H3. Would still be good to confirm.)
4. withinDistance - is there a useful alternative for this where the distance is measured in ZonalIDs at a specified resolution?
5. Crosses - is this valid concept for (single) ZonalIDs?

**Comment by jerstlouis** [comment]
Closing this issue as it is mostly obsoleted by events.

The topological functions are no longer functionality defined by OGC API - DGGS (see also https://github.com/opengeospatial/ogcapi-discrete-global-grid-systems/issues/24#issuecomment-2495529420).

The reasoning is that clients should not rely on Web APIs to determine zone relationships, since that is very inefficient. Instead they should have their own local software library with a built-in understanding of the DGGRS they wish to use.

The clarifications from @rggibb on the concepts of siblings and parents are still relevant.

Regarding _overlaps_, my own realization is that by definition zone of a particular refinement level can never overlap.
The concept of overlap is also related to the new definition of `sub-zones` which is key to the Zone Data retrieval i.e., zones of a finer refinement level at least partially contained within a parent zone. i.e., sub-zones are the zones at a finer level overlapping a parent zone.

Zone Queries can include a CQL2 filter which can include all DE9IM spatial queries (e.g., `S_INTERSECTS()`).

So in a sense I think the API preserves some of the spirit of these topological / query functionalities, as far as they are relevant to a Web API. Comprehensive topological functionality between zones of one or more DGGRS would be more appropriate for a DGGRS abstraction software library than for a Web API.
