### ISSUE TITLE
Some Questions for DGGS API

### ISSUE THREAD

**Issue by ILoveStudying** [opengeospatial/ogcapi-discrete-global-grid-systems#51]
From my perspective,  the current DGGS API returns geometries. In this way, the client does all the subsequent calculations via downloading some local libraries. However, Is it necessary to download large numbers of libraries to support different applications? To be further, shall we need a unified program to address the above-mention problem so that users can implement them directly?

We think there could be another DGGS API idea:  we can operate various calculations such as spatial measurement directly based on the DGGS zoneid such as GeoSOT zoneid algebra. By this means. the server could directly return the results instead of geometries so that the user could implement business applications without understanding the complicated DGGS models but can utilize the convenience of DGGS for integration of data from multi-resources.

The second question is in the following:
For the current DGGS API, where are the APIs for the queries of the neighbor grids and the parent or child nodes? Given a polygon, how do I retrieve the range of the included grids?

**Comment by jerstlouis** [comment]
@ILoveStudying Thank you for asking these questions and very sorry if no one reached out directly to you to provide answers.

> From my perspective, the current DGGS API returns geometries. 

I am not sure what you meant there by the API returning _geometries_. The latest candidate OGC API - DGGS Standard, now in [RFC period](https://www.ogc.org/requests/ogc-requests-public-comment-on-candidate-ogc-api-dggs-standard/), primarily supports one or both of these tasks:
- Zone Data Retrieval - Returning data for a particular zone i.e., _"What is here?"_
- Zone Queries - Returning list of zones matching a particular query i.e., _"Where is here?"_

For zone data, either DGGS-optimized encodings or traditional interoperable geospatial data format is what is returned, with data at a particular depth relative to the parent zone for which it is being requested.

For zone queries, list of zones are expressed as zone IDs (simple array of string identifiers for the mandatory JSON representation).

> In this way, the client does all the subsequent calculations via downloading some local libraries. However, Is it necessary to download large numbers of libraries to support different applications?

I would not advise clients to "download" DGGS libraries at runtime.
Rather, a client for OGC API - DGGS should be built with support for one or more Discrete Global Grid Reference Systems (DGGRS), which might be achieved by using one or more library each providing support for one or more DGGRS.

In my own opinion, the API is most useful and efficient when both the client and the server have a shared understanding of a common DGGRS, and greater interoperability is achieved by supporting more DGGRSs on both server and client.

Although the API is completely agnostic of a DGGRS, and a DGGRS registery is planned with the idea of allowing the flexibility of registering multiple DGGRSs, ideal efficiency would be achieved by a large number of deployments / datasets implementing a common DGGRS. One or more DGGRSs might pick up more momentum than others.

> To be further, shall we need a unified program to address the above-mention problem so that users can implement them directly?

This is an implementation decision, but I am planning the development of an open-source library to facilitate support for a number of DGGRSs. 

> By this means. the server could directly return the results instead of geometries

The Zone Query requirements class allows the server to return the results as zone IDs.
But the DGGS infrastructure can be used as the backend of an OGC API implementation, allowing to support OGC API - Features and OGC API - Coverages to return results as feature collections or gridded coverages. These collections could also be the results of processing workflows using the virtual Collection Output of Processes - Part 3. CQL2 can also be used in conjunction with Features and Coverages to define complex queries. DGGS infrastructure can be used in the backend to do all this internally with simple zone ID operations, without the need for OGC API - DGGS to be involved at all in the client/server communication.

OGC API - DGGS is mostly targeting clients (and servers also acting as clients for data integration) which are DGGS-aware.

> For the current DGGS API, where are the APIs for the queries of the neighbor grids and the parent or child nodes?

The topological relationships are recommended to be included in the Zone Information resource (`.../dggs/{dggrsId}/zones/{zoneId}`) using the link relation types `[ogc-rel:dggs-zone-parent]`, `[ogc-rel:dggs-zone-child]` and `[ogc-rel:dggs-zone-neighbor]`, but this is only a recommendation for purposes of demonstration / education / debugging. Clients should not rely on Web APIs to determine zone relationships, since that is very inefficient. Instead they should have their own local software library with a built-in understanding of the DGGRS they wish to use.

> Given a polygon, how do I retrieve the range of the included grids?

The [Zone Query](https://docs.ogc.org/DRAFTS/21-038.html#rc_zone-query) requirements class plus the [CQL2 filtering of Zone Queries](https://docs.ogc.org/DRAFTS/21-038.html#rc_zone-query-cql2-filter) can be used for this purpose if the server supports the [CQL2 Basic Spatial Functions with additional Spatial Literals requirements class](https://docs.ogc.org/is/21-065r2/21-065r2.html#basic-spatial-functions-plus).

For example:

https://maps.gnosis.earth/ogcapi/collections/gebco/dggs/ISEA3H/zones?filter=S_INTERSECTS(rec.geom,POLYGON((-64.8%2032.3,-65.5%2018.3,-80.3%2025.2,-64.8%2032.3)))&zone-level=5

https://maps.gnosis.earth/ogcapi/collections/gebco/dggs/ISEA3H/zones?filter=S_INTERSECTS(rec.geom,POLYGON((-64.8%2032.3,-65.5%2018.3,-80.3%2025.2,-64.8%2032.3)))&zone-level=5&f=json

Closing this issue as completed.

Please re-open it or file a new issue if further clarifications are needed.
