### ISSUE TITLE
Decision Needed on DGGS Identifier nomenclature for OGC API DGGS

### ISSUE THREAD

**Issue by geofizzydrink** [opengeospatial/ogcapi-discrete-global-grid-systems#56]
Hi All,

I think we need to hold a SWG vote on the nomenclature of the DGGS Identifier for use in describing the OGC API DGGS. We have two different but equally valid naming schemes that we could use for DGGS infrastructure Identifiers:

1. **_{dggsID}_** 
    - This follows the same basic pattern used throughout the OGC API schemas of `<resourceType>+"ID"`.
    - For example: `collectionID`, `itemID`, `processID`, `jobID`, etc...
    - If we follow this naming convention we will be 100% in sync with the other OGC API specs since a DGGS can be viewed as a "resourceType".
    - This also allows for an individual DGGS instance to be named anything (from the API perspective) despite what the "dggsRSID" actually is.
        - This could also open up the possibility of different instances of the same DGGS resource being accessed via different OGC API DGGS endpoints. (e.g. one might have an instance of the "H3" DGGS implemented on the API Server but wish to expose it as `/dggs/bobsDGGS/...` instead of `/dggs/h3/...`).
        - The upside of this approach is that if the _dggsRSID_ is complicated and/or not "pretty" to the human eye (e.g. **_TerraNexus_S_IT9_GRS80_2d10b58e2088c7e2_**) this could be replaced by a simpler _dggsID_ (such as, **_TerraNexus1_**).
        - The downside of this approach is that it could lead to a dislocation, or confusion, between an arbitrary _dggsID_ and the precise _dggsRSID_ that it is referring to. This could potentially lead to complications in machine driven determination of different instances of the same DGGS.

2. **_{dggsRSID}_**
    - This follows the approach defined in OGC Abstract Specification Topic 21 (ISO 19170-1:2021) where a DGGS is actually described as a DGGS Reference System where each DGGS_RS will have a unique identifier - i.e. a dggsRS**ID**.
    - This approach will provide explicit linkage between OGC API DGGS resource endpoints/definitions and the specific DGGS they are relevant to.
    - By forcing this explicit naming via the dggsRSID we also provide a tighter coupling with the (yet to be published) OGC DGGS Registry - which is proposed to serve a similar role to that of the CRS Registry by recording and making accessible the standardised definition of all "registered" DGGS specifications.
        - The counter to this would be that, so long as the OGC API DGGS Core definition elements correctly refer to a valid "registered" dggsRSID the OGC API DGGS should still function correctly.

What do people think? 

Should we use **_dggsID_**, or, **_dggsRSID_** for the OGC API DGGS schema?

If we have quorum during the next DGGS SWG telecon I would like us to vote on this? if not, we can vote on this during the October Members Meeting in Singapore.

**Comment by jerstlouis** [comment]
As hinted at in #57, my preference lies with the simpler `{dggsID}`.
However, we should make it clear that by `{dggsID}` we identify both a specific discrete global grid as well as a specific indexing scheme, which corresponds to a _DGGS Reference System ID_ in Topic 21.

**Comment by AkexStar** [comment]
I prefer to `{dggsID}`, and agree with @jerstlouis .

**Comment by jerstlouis** [comment]
Although we are sticking to the `.../dggs/` paths, after discussion with the editing groups, I have updated the spec in bfb9b2adcee1bded97122c9bfd6a10e49ced0513 to use `{dggrsId}` to really highlight the fact that that these are DGGRSs implying a particular indexing scheme.

**Comment by geofizzydrink** [comment]
Let's close this issues - we have settled on the use of {dggrsId}.

**Comment by jerstlouis** [comment]
The distinction between DGGS and DGGRS has been addressed in the Terms and Definitions of the candidate OGC API - DGGS Standard.

Based on those clarifications, the resources at `.../dggs/{dggrsId}` really represent a Discrete Global Grid Reference System (DGGRS), which is:
- a particular Discrete Global Grid Hierarchy (DGGH), plus
- a particular Zone Identifier/Indexing Reference System (ZIRS), as well as
- a particular sub-zone ordering -- a new concept introduced for local indexing within a particular zone to support the DGGS-optimized DGGS-JSON and DGGS-FG-JSON encodings.

Annex B provides 3 examples of DGGRSs (GNOSISGlobalGrid, ISEA3H and ISEA9R).

A DGGH is a hierarchy of Discrete Global Grids at multiple refinement levels, including all specified parameters (e.g., reference Earth model, polyhedron orientation, etc.). For example, a hierarchy of ISEA3H grids with the specific orientation defined in Annex B, but using any indexing or sub-zone ordering, is an example of a DGGH.

A Discrete Global Grid System (DGGS), as defined in Topic 21 and OGC API - DGGS, is an integrated system supporting one or more DGGRS, together with functions for quantization, zone queries and interoperability. Implementations of OGC API - DGGS are examples of a DGGS.

Therefore, we kept `{dggrsId}`, even though the access mechanism path is `.../dggs`, because all DGGRS fall within the OGC API - DGGS access mechanism.

In our own implementation, we use `/ogcapi/dggrs/{dggrsId}` (note the **dggrs** in this case) for hosting the definition of the DGGRS (as opposed to the **description** which is at `.../dggs/{dggrsId}`), as defined in Annex B and as linked to by the link relation type `[ogc-rel:dggrs-definition]`. For example: https://maps.gnosis.earth/ogcapi/dggrs/ISEA3H . This resource is required to be linked to from the description, but can live anywhere (as another example, this could alternatively be a link to a JSON representation available from the OGC DGGRS registry on the OGC Definition Server once this is set up).
