### ISSUE TITLE
Decision needed on nomenclature for "Zonal Identifier" in the OGC API DGGS Specification.

### ISSUE THREAD

**Issue by geofizzydrink** [opengeospatial/ogcapi-discrete-global-grid-systems#57]
Hi All,

Here's another issue I would like us to vote on (similar to the dggsRSID vs dggsID decision we need to make).

OGC Abstract Spec Topic 21 (ISO 19170-1:2021) describes "cell" identifiers as "**_zonal_**" identifiers, recognising that a more appropriate naming convention for a 2D cell in a multi-dimensional (spatio-temporal) infrastructure such as a DGGS is "**_zone_**", and when referring to a collection of one or more "zones" it is appropriate to use the term "**_zonal_**".

However, in terms of the naming conventions for resource elements of OGC APIs, using the term **_{zonalID}_** to access the description (or data holdings of) an individual DGGS Zone (e.g. `/dggs/{dggsID}/zones/{zonalID}`) appears both cumbersome and presents a possible risk of someone miss reading the OGC API DGGS specification depending on the font used to publish the specification (i.e. it is possible in a number of fonts to missread lowercase "l" and uppercase "I"). In this context it might be better to use the term "**_zoneID_**" instead of **_zonalID_**.

So, I would like to ask the question, which naming convention to we want to enshrine in the OGC API DGGS Specification:
1. **_{zoneID}_**
    - following a very similar naming convention to that of the other OGC APIs
    - simpler and less prone to missreading due to font representations; or,
2. **_{zonalID}_**
    - following the explicit naming convention defined in OGC Abstract Spec Topic 21 (ISO 19170-1:2021).

As the the _dggsRSID_ vs _dggsID_ question, I'd like us to hold a SWG vote on this during the next telecon if we have quorum.

**Comment by AkexStar** [comment]
Prefer to {zoneID} and {dggsID}
It's important for endPoints to be simpler and shorter.

**Comment by jerstlouis** [comment]
Closing this issue since this has been agreed upon and resolved.

A `zone ID` is the exact same thing as a `zonal identifier` and this has been clarified in the Terms and Definitions.
We use the shorter / more familiar `{zoneId}` form in the example API definitions, though at least from my own understanding of things, the actual names of the path parameters in API definitions are not something normative.

Regarding `{dggrsId}` vs. `{dggsId}`, this was the separate issue #56, to which I've added [further clarifications](https://github.com/opengeospatial/ogcapi-discrete-global-grid-systems/issues/56#issuecomment-2495516726).
